Replace command level item with object, Update command level, Add Act…
IBM/vscode-ibmi-projectexplorer pull request #219
Opened 2023-09-21 19:51 UTC by irfanshar

…ion to toggle failures, Add Action to filter by severity level

2023-09-22 16:01 UTC, edmundreinhardt requested changes

2023-09-22 16:01 UTC, edmundreinhardt commented on src/views/jobLog/log.ts
> +        command => command.failed === this.showFailedCommands
you already know the `showFailedCommands` is `true`
so why not just have `command.failed`

2023-09-22 21:30 UTC, edmundreinhardt requested changes
Behaviour changes
1) the icon for showing only failing commands, it should be a red x of some sort, it should appear differently whether it si toggled on or off
2) the filter by severity should be shown for the same scope, i.e. for all the entire build.
i.e. it will apply to all the commands for the current build.  
3) The copy command should copy the command (which is now a child) rather than just the name of the targer object

2023-09-26 21:46 UTC, edmundreinhardt approved these changes

2023-09-26 21:46 UTC, edmundreinhardt commented on src/views/jobLog/index.ts
> +          element.toggleShowFailed();
hopefully these never get out of sync.  It would be safer to set the desired value.  Although i see this works.

2023-09-26 21:46 UTC, merged

2023-09-26 21:51 UTC, edmundreinhardt commented
Hmm, I am not seeing the action toggle

2023-09-27 13:20 UTC, irfanshar commented
> Hmm, I am not seeing the action toggle

The two commands that use toggle are ```vscode-ibmi-projectexplorer.jobLog.showOnlyFailedJobs``` and ```vscode-ibmi-projectexplorer.jobLog.showAllJobs```.  I felt these were more descriptive names rather than two different "toggle" commands.

2023-09-27 13:41 UTC, edmundreinhardt commented
when I tested, and clicked the button, it did not toggle

2023-09-27 14:50 UTC, irfanshar commented
> when I tested, and clicked the button, it did not toggle

Hmm, odd it is toggling on my end. Can you attach a copy of the joblog.json you're using to test?