For unspecified build commands, prefill prompt with BOB commands and invoke command after prompting
IBM/vscode-ibmi-projectexplorer pull request #284
Opened 2023-12-09 13:01 UTC by edmundreinhardt

When there is no build or compile command in the iproj.json, invoking the build or compile prompts the user for a new command.

### For Build
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/2118f50d-5eb6-42ed-a3b6-2819427f7ce0)
 
if you press 'Set Build Command', the prompt is *now* prefilled with the BOB build command
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/004d4bc5-bcab-41e0-b62c-111c9853be3f)

After specifying the command, the command is *now* actually invoked instead of forcing the user to invoke it again.
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/7ade96fa-76b5-4935-a50c-fc04100c64ec)

### For Compile
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/5601e863-2f20-4756-9440-5320d922cd64)

if you press 'Set Build Command', the prompt is *now* prefilled with the BOB build command
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/127a89d5-a045-4643-aae3-0619d959dea1)

![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/11184579/559cf632-3d30-427f-8156-72e55b27d87f)

2023-12-09 13:04 UTC, edmundreinhardt commented
@worksofliam I invite your scrutiny as this is my first time with node.js callbacks

2023-12-12 19:50 UTC, worksofliam commented on src/iproject.ts
> +            .then(async () =>
Async keyword not needed here as there is no return so we don't have to wait.

2023-12-12 19:50 UTC, worksofliam commented on src/iproject.ts
> +              {this.runBuildOrCompileCommand(isBuild, fileUri);}
Same here with `async`

2023-12-12 19:57 UTC, worksofliam requested changes
Please consider using a different approach instead of changing `then`. Perhaps one of these?

```ts
          window.showErrorMessage(l10n.t('Project\'s build command not set'), l10n.t('Set Build Command'))
            .then((item) => {
              if (item === l10n.t('Set Build Command')) {
                commands.executeCommand(`vscode-ibmi-projectexplorer.projectExplorer.setBuildCommand`, this).then(res => {
                  this.runBuildOrCompileCommand(isBuild, fileUri);
                });
              }
            })
```
          const selection = await window.showErrorMessage(l10n.t('Project\'s build command not set'), l10n.t('Set Build Command'));
          if (selected === l10n.t('Set Build Command')) {
            await commands.executeCommand(`vscode-ibmi-projectexplorer.projectExplorer.setBuildCommand`, this);
            this.runBuildOrCompileCommand(isBuild, fileUri);
          }
```ts

```

2023-12-12 20:30 UTC, worksofliam approved these changes
Code is much nicer now. Thanks @edmundreinhardt!

2023-12-12 22:09 UTC, merged