Add scanning for sub projects
IBM/vscode-ibmi-projectexplorer pull request #476
Opened 2024-05-24 12:21 UTC by SanjulaGanepola

2024-05-24 19:19 UTC, edmundreinhardt requested changes

2024-05-24 20:07 UTC, SanjulaGanepola commented on src/iproject.ts
> +    for await (const uri of subDirectoryUris) {
When you say number of directories to scan, do you mean the maximum number of directories to scan at any level or the maximum number of levels to scan (defaulted at 2)?

To scan a directory I am using the VS Code `FileSystem.readDirectory` API which retrieves all directories at the given path. It doesn't look like it has any parameters at the moment to limit the number of retrieved directories.

2024-05-24 20:29 UTC, SanjulaGanepola commented on src/iproject.ts
> +    for await (const uri of subDirectoryUris) {
If it is the depth we want as a setting, I can add that. I will keep the default as 2

2024-05-24 22:40 UTC, SanjulaGanepola commented
@edmundreinhardt I have pushed changes (https://github.com/IBM/vscode-ibmi-projectexplorer/pull/476/commits/705d6c5e7c850337d328fa04064fa49b42d3399d) to include what we discussed with William:

1. `Scan For Projects` action to manually trigger a re-scan which can be used if the user manually git clones a project from the terminal:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/32170854/696abe80-56b9-46e0-a22a-a0f44f1c62d0)

2. New preference to set scan depth:
![image](https://github.com/IBM/vscode-ibmi-projectexplorer/assets/32170854/5bf8f945-25a5-4abc-8847-4b76b1264247)

3. Initial scan only happens now if the workspace folder does not have an `iproj.json`

4. Updated the `scanAndAddSubIProjects` API to take in a `uri` so that it can be used by IBM i Developer.

2024-05-25 02:19 UTC, edmundreinhardt requested changes

2024-05-25 02:19 UTC, edmundreinhardt commented on src/projectManager.ts
> +            if (currentDepth != scanDepth) {
If we find a project at 1 level, we should not look in its subdirectories

2024-05-27 13:02 UTC, edmundreinhardt approved these changes
Looks good, the recursive approach should work fine

2024-05-27 13:15 UTC, william-xiang approved these changes
Great job!

2024-05-27 18:12 UTC, SanjulaGanepola commented
I will merge this PR later on in case we need a new Project Explorer release for v2 with fixes that exclude this change

2024-05-27 18:40 UTC, edmundreinhardt commented
> I will merge this PR later on in case we need a new Project Explorer release for v2 with fixes that exclude this change

agreed

2024-06-10 14:34 UTC, merged